apiVersion: v2
kind: ConfigMap
metadata:
  name: chirpstack-gb
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
data:
  chirpstack-gateway-bridge.toml: |
    # See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
    # configuration example and documentation.
    {{- if .Values.gb.useCommonMqttSettings }}
      # MQTT authentication.
      [integration.mqtt.auth]
      # Type defines the MQTT authentication type to use.
      #
      # Set this to the name of one of the sections below.
      type="generic"

        # Generic MQTT authentication.
        [integration.mqtt.auth.generic]
        # MQTT servers.
        #
        # Configure one or multiple MQTT server to connect to. Each item must be in
        # the following format: scheme://host:port where scheme is tcp, ssl or ws.
        # MQTT server (e.g. scheme://host:port where scheme is tcp, ssl or ws)
        servers=["tcp://{{ $.Values._common.mqtt.host }}:{{ $.Values._common.mqtt.port }}"]

        # Connect with the given username (optional)
        username="{{ $.Values._common.mqtt.username | default "" }}"

        # Connect with the given password (optional)
        password="{{ $.Values._common.mqtt.password | default "" }}"

        # Quality of service level
        #
        # 0: at most once
        # 1: at least once
        # 2: exactly once
        #
        # Note: an increase of this value will decrease the performance.
        # For more information: https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels
        qos={{ $.Values._common.mqtt.qos | default 2 }}

        # Clean session
        #
        # Set the "clean session" flag in the connect message when this client
        # connects to an MQTT broker. By setting this flag you are indicating
        # that no messages saved by the broker for this client should be delivered.
        clean_session={{ $.Values._common.mqtt.cleanSession | default false }}

        # Client ID
        #
        # Set the client id to be used by this client when connecting to the MQTT
        # broker. A client id must be no longer than 23 characters. If left blank,
        # a random id will be generated by ChirpStack.
        client_id="{{ $.Values._common.mqtt.clientId | default "chirpstack" }}"

        # CA certificate file (optional)
        #
        # Use this when setting up a secure connection (when server uses ssl://...)
        # but the certificate used by the server is not trusted by any CA certificate
        # on the server (e.g. when self generated).
        ca_cert="{{ $.Values._common.mqtt.caCert | default "" }}"

        # TLS certificate file (optional)
        tls_cert="{{ $.Values._common.mqtt.tlsCert | default "" }}"

        # TLS key file (optional)
        tls_key="{{ $.Values._common.mqtt.tlsKey | default "" }}"
    {{- end }}


    {{- if .Values.gb.useCommonRegionSettings }}
      [backend.basic_station]
    {{- range $index, $region := .Values._common.region }}
      {{- $regionData := $.Files.Get (printf "configurations/chirpstack/regions/region_%s.json" $region.name) | fromJson }}
      {{- if $regionData.regions }}
        {{- range $region := $regionData.regions }}
          {{- if $region.gateway }}
            {{- $frequencies := list }}  {{/* Initialize an empty list */}}
            
            {{- range $channel := $region.gateway.channels }}
              {{- if $channel.frequency }}
                {{- $frequencyInt := int $channel.frequency }}  {{/* Cast frequency to int */}}
                {{- $frequencies = append $frequencies $frequencyInt }}  {{/* Append frequency */}}
              {{- end }}
            {{- end }}
            
            {{- if gt (len $frequencies) 0 }}
              {{- $minFrequency := (index $frequencies 0) }}  {{/* Start with the first frequency as the minimum */}}
              {{- $maxFrequency := (index $frequencies 0) }}  {{/* Start with the first frequency as the maximum */}}
              
              {{- range $frequency := $frequencies }}
                {{- if lt $frequency $minFrequency }}
                  {{- $minFrequency = $frequency }}  {{/* Update min if current frequency is lower */}}
                {{- end }}
                {{- if gt $frequency $maxFrequency }}
                  {{- $maxFrequency = $frequency }}  {{/* Update max if current frequency is higher */}}
                {{- end }}
              {{- end }}

      region={{ upper $region.name }}
      frequency_min={{ $minFrequency }}
      frequency_max={{ $maxFrequency }}
            {{- else }}
      region={{ upper $region.name }}
      frequency_min="N/A"
      frequency_max="N/A"
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}

    {{- if .Values.gb.config }}
    {{ .Values.gb.config | nindent 4 }}
    {{- end }}










