{{- $settings := dict "firstRegion" "" "frequencyMin" 0 "frequencyMax" 0 }}

{{ with .Values._common.region }}
  {{- $selectedRegion := index . 0 }}
  {{- $regionData := $.Files.Get (printf "configurations/region_%s.json" $selectedRegion.name) | fromJson }}
  
  {{- if $regionData.regions }}
    {{- range $region := $regionData.regions }}
      {{- if $region.gateway }}
        
        {{- $frequencies := list }}  {{/* Initialize an empty list */}}
        
        {{- range $channel := $region.gateway.channels }}
          {{- if $channel.frequency }}
            {{- $frequencyInt := int $channel.frequency }}  {{/* Cast frequency to int */}}
            {{- $frequencies = append $frequencies $frequencyInt }}  {{/* Append frequency */}}
          {{- end }}
        {{- end }}
        
        {{- if gt (len $frequencies) 0 }}
          {{- $minFrequency := (index $frequencies 0) }}  {{/* Start with the first frequency as the minimum */}}
          {{- $maxFrequency := (index $frequencies 0) }}  {{/* Start with the first frequency as the maximum */}}
          
          {{- range $frequency := $frequencies }}
            {{- if lt $frequency $minFrequency }}
              {{- $minFrequency = $frequency }}  {{/* Update min if current frequency is lower */}}
            {{- end }}
            {{- if gt $frequency $maxFrequency }}
              {{- $maxFrequency = $frequency }}  {{/* Update max if current frequency is higher */}}
            {{- end }}
          {{- end }}
          
          {{- $_ := set $settings "firstRegion" (upper $selectedRegion.name) }}
          {{- $_ := set $settings "frequencyMin" $minFrequency }}
          {{- $_ := set $settings "frequencyMax" $maxFrequency }}
        
        {{- else }}
          {{- $_ := set $settings "firstRegion" (upper $selectedRegion.name) }}
          {{- $_ := set $settings "frequencyMin" 7 }}
          {{- $_ := set $settings "frequencyMax" 5 }}
        {{- end }}
        
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

apiVersion: v2
kind: ConfigMap
metadata:
  name: chirpstack-gb
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
data:
  chirpstack-gateway-bridge.toml: |
    [general]
    {{- if .Values.gb.config.general }}
    log_level = {{ .Values.gb.config.general.logLevel | default 4 }}
    log_json = {{ .Values.gb.config.general.logJson | default false }}
    log_to_syslog = {{ .Values.gb.config.general.logToSyslog | default false }}
    {{- else }}
    log_level = 4 
    log_json = false 
    log_to_syslog = false 
    {{- end }}

    [filters]
    {{- if .Values.gb.config.filters }}
    {{- with .Values.gb.config.filters }}
    net_ids = {{ .netIds | default "[]" | toJson }}
    join_euis = {{ .joinEuis | default "[]" | toJson }}
    {{- end}}
    {{- else }}
    net_ids=[
    ]
    {{- end }}

    [backend]
    {{- if .Values.gb.config.backend }} 
    type = "{{ .Values.gb.config.backend.type | default "semtech_udp" }}"
    {{- else }}
    type="semtech_udp"
    {{- end }}

      [backend.semtechUdp]
    {{- if and .Values.gb.config.backend .Values.gb.config.backend.semtechUdp }}
    {{- with .Values.gb.config.backend.semtechUdp }}
      udp_bind = "{{ .udpBind | default "0.0.0.0:1700" }}"
      fake_rx_time = {{ .fakeRxTime | default false }}
    {{- end }}
    {{- else }}
      udp_bind = "0.0.0.0:1700"
      fake_rx_time=false
    {{- end }}

      [backend.concentratord]
    {{- if and .Values.gb.config.backend .Values.gb.config.backend.concentratord }}
    {{- with .Values.gb.config.backend.concentratord }}
      event_url = "{{ .eventUrl | default "ipc:///tmp/concentratord_event" }}"
      command_url = "{{ .commandUrl | default "ipc:///tmp/concentratord_command" }}"
    {{- end }}
    {{- else }}
      event_url="ipc:///tmp/concentratord_event"
      command_url="ipc:///tmp/concentratord_command"
    {{- end }}
    
      [backend.basicStation]    
    {{- if and .Values.gb.config.backend .Values.gb.config.backend.basicStation }}
      {{- with .Values.gb.config.backend.basicStation }}
      bind = "{{ .bind | default ":3001" }}"
      tls_cert = "{{ .tlsCert | default "" }}"
      tls_key = "{{ .tlsKey | default "" }}"
      ca_cert = "{{ .caCert | default "" }}"
      stats_interval = "{{ .statsInterval | default "30s" }}"
      ping_interval = "{{ .pingInterval | default "1m0s" }}"
      timesync_interval = "{{ .timesyncInterval | default "0s" }}"
      read_timeout = "{{ .readTimeout | default "1m5s" }}"
      write_timeout = "{{ .writeTimeout | default "1s" }}"
      region = "{{ $settings.firstRegion | default "EU868" }}"
      frequency_min = {{ $settings.frequencyMin | default 0 }}
      frequency_max = {{ $settings.frequencyMax | default 0 }}
      {{- end }}
    {{- else }}
      bind=":3001"
      tls_cert=""
      tls_key=""
      ca_cert=""
      stats_interval="30s"
      timesync_interval="0s"
      read_timeout="1m5s"
      region = "{{ $settings.firstRegion | default "EU868" }}"
      frequency_min = {{ $settings.frequencyMin | default 0 }}
      frequency_max = {{ $settings.frequencyMax | default 0 }}
    {{- end }}

    [integration]
    {{- if .Values.gb.config.integration }}
    marshaler = "{{ .Values.gb.config.integration.marshaler | default "protobuf" }}"
    {{- else }}
    marshaler = "protobuf"
    {{- end }}

      [integration.mqtt]
    {{- if and .Values.gb.config.integration .Values.gb.config.integration.mqtt }}
      {{- with .Values.gb.config.integration.mqtt }}
      event_topic_template = "{{ .eventTopicTemplate | default "gateway/{{ .GatewayID }}/event/{{ .EventType }}" }}"
      state_topic_template = "{{ .stateTopicTemplate | default "gateway/{{ .GatewayID }}/state/{{ .StateType }}" }}"
      command_topic_template = "{{ .commandTopicTemplate | default "gateway/{{ .GatewayID }}/command/#" }}"
      state_retained = {{ .stateRetained | default true | toJson }}
      keep_alive = "{{ .keepAlive | default "30s" }}"
      max_reconnect_interval = "{{ .maxReconnectInterval | default "1m0s" }}"
      terminate_on_connect_error = {{ .terminateOnConnectError | default false }}
      {{- end }}
    {{- else }}
      event_topic_template = "gateway/{{` .GatewayID `}}/event/{{` .EventType `}}"
      state_topic_template = "gateway/{{` .GatewayID `}}/state/{{` .EventType `}}"
      command_topic_template = "gateway/{{` .GatewayID `}}/command/#"
      state_retained = true 
      keep_alive =  "30s"
      max_reconnect_interval = "1m0s"
      terminate_on_connect_error = false 
    {{- end }}

      [integration.mqtt.auth]
    {{- if and .Values.gb.config.integration .Values.gb.config.integration.mqtt .Values.gb.config.integration.mqtt.auth }}
      type = "{{ .Values.gb.config.integration.mqtt.auth.type | default "generic" }}"
    {{- else }}
      type = "generic"
    {{- end }}

        [integration.mqtt.auth.generic]
    {{- if .Values.gb.useCommonMqttSettings }}
        servers = "tcp://{{ $.Values._common.mqtt.host | default "127.0.0.1" }}:{{ $.Values._common.mqtt.port | default "1883" }}"
        username = "{{ $.Values._common.mqtt.username | default "" }}"
        password = "{{ $.Values._common.mqtt.password | default "" }}"
        qos = {{ $.Values._common.mqtt.qos | default 0 }}
        clean_session = {{ $.Values._common.mqtt.cleanSession | default false }}
        client_id = "{{ $.Values._common.mqtt.clientId | default "chirpstack" }}"
        ca_cert = "{{ $.Values._common.mqtt.caCert | default "" }}"
        tls_cert = "{{ $.Values._common.mqtt.tlsCert | default "" }}"
        tls_key = "{{ $.Values._common.mqtt.tlsKey | default "" }}"
    {{- else }}
    {{- if and .Values.gb.config.integration .Values.gb.config.integration.mqtt .Values.gb.config.integration.mqtt.auth .Values.gb.config.integration.mqtt.auth.generic }}
        {{- with .Values.gb.config.integration.mqtt.auth.generic }}
        servers = {{ .servers | default (list "tcp://127.0.0.1:1883") | toJson }}
        username = "{{ .username | default "" }}"
        password = "{{ .password | default "" }}"
        qos = {{ .qos | default 0 }}
        clean_session = {{ .cleanSession | default true }}
        client_id = "{{ .clientId | default "" }}"
        ca_cert = "{{ .caCert | default "" }}"
        tls_cert = "{{ .tlsCert | default "" }}"
        tls_key = "{{ .tlsKey | default "" }}"
        {{- end }}
    {{- else }}
        servers = "tcp://127.0.0.1:1883"
        username = ""
        password = ""
        qos = 0
        clean_session = true
        client_id = ""
        ca_cert = ""
        tls_cert = ""
        tls_key = ""
    {{- end }}
    {{- end }}


        [integration.mqtt.auth.gcpCloudIotCore]
    {{- if and .Values.gb.config.integration .Values.gb.config.integration.mqtt .Values.gb.config.integration.mqtt.auth .Values.gb.config.integration.mqtt.auth.gcpCloudIotCore }}
        {{- with .Values.gb.config.integration.mqtt.auth.gcpCloudIotCore }}
        server = "{{ .server | default "ssl://mqtt.googleapis.com:8883" }}"
        device_id = "{{ .deviceId | default "" }}"
        project_id = "{{ .projectId | default "" }}"
        cloud_region = "{{ .cloudRegion | default "" }}"
        registry_id = "{{ .registryId | default "" }}"
        jwt_expiration = "{{ .jwtExpiration | default "24h0m0s" }}"
        jwt_key_file = "{{ .jwtKeyFile | default "" }}"
        {{- end }}
    {{- else }}
        server = "ssl://mqtt.googleapis.com:8883" 
        device_id =  "" 
        project_id = "" 
        cloud_region = ""
        registry_id = "" 
        jwt_expiration = "24h0m0s" 
        jwt_key_file = "" 
    {{- end }}

        [integration.mqtt.auth.azureIotHub]
    {{- if and .Values.gb.config.integration .Values.gb.config.integration.mqtt .Values.gb.config.integration.mqtt.auth .Values.gb.config.integration.mqtt.auth.azureIotHub }} 
        {{- with .Values.gb.config.integration.mqtt.auth.azureIotHub }}
        device_connection_string = "{{ .deviceConnectionString | default "" }}"
        sas_token_expiration = "{{ .sasTokenExpiration | default "24h0m0s" }}"
        device_id = "{{ .deviceId | default "" }}"
        hostname = "{{ .hostname | default "" }}"
        tls_cert = "{{ .tlsCert | default "" }}"
        tls_key = "{{ .tlsKey | default "" }}"
        {{- end }}
    {{- else }}
        device_connection_string = "" 
        sas_token_expiration = "24h0m0s"
        device_id = ""
        hostname = ""
        tls_cert = "" 
        tls_key = "" 
    {{- end }}

    [metrics]
    {{- if .Values.gb.config.metrics }}
      {{- with .Values.gb.config.metrics }}
      endpoint_enabled = {{ .endpointEnabled | default false }}
      bind = "{{ .bind | default "" }}"
      {{- end }}
    {{- else }}
      endpoint_enabled = false 
      bind = ""
    {{- end }}

    [meta_data]
      [meta_data.static]
    {{- if and .Values.gb.config.metaData .Values.gb.config.metaData.static }}
    {{ . | nindent 6}}
    {{- end }}

      [metaData.dynamic]
    {{- if and .Values.gb.config.metaData .Values.gb.config.metaData.dynamic }}
      {{- with .Values.gb.config.metaData.dynamic }}
      execution_interval = "{{ .executionInterval | default "1m0s" }}"
      max_execution_duration = "{{ .maxExecutionDuration | default "1s" }}"
      split_delimiter = "{{ .splitDelimiter | default "=" }}"
      {{- end }}
    {{- else }}
      execution_interval = "1m0s"
      max_execution_duration = "1s" 
      split_delimiter = "=" 
    {{- end }}

      [meta_data.dynamic.commands]
    {{- if and .Values.gb.config.metaData .Values.gb.config.metaData.dynamic.commands }}
    {{ . | nindent 6}}
    {{- end }}

    [commands]
    {{- if .Values.gb.config.commands }}
    {{ . | nindent 6}}
    {{- end }}

    {{- if .Values.gb.configExtra }}
    {{ .Values.gb.configExtra | nindent 4 }}
    {{- end }}