apiVersion: v1
kind: Service
metadata:
  labels:
    app: chirpstack-gb
  name: chirpstack-gb
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
spec:
  ports:
  - name: udp
    port: {{ .Values.chirpstack.service.port }}
    protocol: UDP
    targetPort: {{ .Values.chirpstack.service.port }}
  selector:
    app: chirpstack-gb
  type: {{ .Values.chirpstack.service.type | default "ClusterIP" }}