{{- $namespace := .Values._common.namespace | default "chirpstack" }}
{{- $existingSecret := (lookup "v2" "Secret" $namespace "db-creds") }}
{{- $postgresUser := default (randAlphaNum 64) .Values._common.postgres.postgresUser | b64enc | quote }}
{{- $password := default (randAlphaNum 64) .Values._common.postgres.password | b64enc | quote }}
{{- $role := default (randAlphaNum 64) .Values._common.postgres.role | b64enc | quote }}
{{- $caCert := default "" .Values._common.postgres.caCert | b64enc | quote }}
{{- if $existingSecret }}
{{- $postgresUser = index $existingSecret.data "postgresUser"}}
{{- $password = index $existingSecret.data "password"}}
{{- $role = index $existingSecret.data "role"}}
{{- $caCert = index $existingSecret.data "caCert"}}
{{- end -}}


apiVersion: v1
kind: Secret
metadata:
  name: db-creds
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
  annotations:
    "helm.sh/resource-policy": "keep"
    "helm.sh/hook": pre-install
type: Opaque
data: # base64 encoded twice
  postgresUser: {{ $postgresUser }}
  password: {{ $password }}
  role: {{ $role }}
  caCert: {{ $caCert }}
