{{- if not .Values._common.postgres.external.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
spec:
  selector:
    matchLabels:
      app: postgres 
  serviceName: "postgres"
  replicas: 1 
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag | default "postgres:14-alpine" }}"
        env:
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: adminPassword
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: postgresUser
          - name: DB_ROLE
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: role
          - name: ROLE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-creds
                key: password
          - name: DB_NAME
            value: "{{ .Values._common.postgres.settings.dbName }}"
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.postgres.service.port }}
          name: postgres
        volumeMounts:
          - name: {{ .Values.postgres.volumeMounts.name  }}
            mountPath: {{ .Values.postgres.volumeMounts.mountPath  }}
          - name: initdb
            mountPath: /docker-entrypoint-initdb.d
            subPath: initdb/001-init-chirpstack.sh
          - name: initdb
            mountPath: /docker-entrypoint-initdb.d
            subPath: initdb/002-chirpstack_extensions.sh
          
      volumes:
      - name: initdb
        configMap:
          name: {{ .Values.postgres.volumes.initdb.configMap.name }}
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgres.volumeClaim.resources.requests.storage }}
{{- end }}

