
        # Google Cloud Platform Cloud IoT Core authentication.
        #
        # Please note that when using this authentication type, the MQTT topics
        # will be automatically set to match the MQTT topics as expected by
        # Cloud IoT Core.
        [integration.mqtt.auth.gcp_cloud_iot_core]
        # MQTT server.
        server="ssl://mqtt.googleapis.com:8883"

        # Google Cloud IoT Core Device id.
        device_id=""

        # Google Cloud project id.
        project_id=""

        # Google Cloud region.
        cloud_region=""

        # Google Cloud IoT registry id.
        registry_id=""

        # JWT token expiration time.
        jwt_expiration="24h0m0s"

        # JWT token key-file.
        #
        # Example command to generate a key-pair:
        #  $ ssh-keygen -t rsa -b 4096 -f private-key.pem
        #  $ openssl rsa -in private-key.pem -pubout -outform PEM -out public-key.pem
        #
        # Then point the setting below to the private-key.pem and associate the
        # public-key.pem with this device / gateway in Google Cloud IoT Core.
        jwt_key_file=""


        # Azure IoT Hub
        #
        # This setting will preset uplink and downlink topics that will only
        # work with Azure IoT Hub service.
        [integration.mqtt.auth.azure_iot_hub]

        # Device connection string (symmetric key authentication).
        #
        # This connection string can be retrieved from the Azure IoT Hub device
        # details when using the symmetric key authentication type.
        device_connection_string=""

        # Token expiration (symmetric key authentication).
        #
        # ChirpStack Gateway Bridge will generate a SAS token with the given expiration.
        # After the token has expired, it will generate a new one and trigger a
        # re-connect (only for symmetric key authentication).
        sas_token_expiration="24h0m0s"

        # Device ID (X.509 authentication).
        #
        # This will be automatically set when a device connection string is given.
        # It must be set for X.509 authentication.
        device_id=""

        # IoT Hub hostname (X.509 authentication).
        #
        # This will be automatically set when a device connection string is given.
        # It must be set for X.509 authentication.
        # Example: iot-hub-name.azure-devices.net
        hostname=""

        # Client certificates (X.509 authentication).
        #
        # Configure the tls_cert (certificate file) and tls_key (private-key file)
        # when the device is configured with X.509 authentication.
        tls_cert=""
        tls_key=""


    # Metrics configuration.
    [metrics]

      # Metrics stored in Prometheus.
      #
      # These metrics expose information about the state of the ChirpStack Gateway Bridge
      # instance like number of messages processed, number of function calls, etc.
      [metrics.prometheus]
      # Expose Prometheus metrics endpoint.
      endpoint_enabled=false

      # The ip:port to bind the Prometheus metrics server to for serving the
      # metrics endpoint.
      bind=""


    # Gateway meta-data.
    #
    # The meta-data will be added to every stats message sent by the ChirpStack Gateway
    # Bridge.
    [meta_data]

      # Static.
      #
      # Static key (string) / value (string) meta-data.
      [meta_data.static]
      # Example:
      # serial_number="A1B21234"



      # Dynamic meta-data.
      #
      # Dynamic meta-data is retrieved by executing external commands.
      # This makes it possible to for example execute an external command to
      # read the gateway temperature.
      [meta_data.dynamic]

      # Execution interval of the commands.
      execution_interval="1m0s"

      # Max. execution duration.
      max_execution_duration="1s"

      # Split delimiter.
      #
      # When the output of a command returns multiple lines, ChirpStack Gateway Bridge
      # assumes multiple values are returned. In this case it will split by the given delimiter
      # to obtain the key / value of each row. The key will be prefixed with the name of the
      # configured command.
      split_delimiter="="


      # Commands to execute.
      #
      # The value of the stdout will be used as the key value (string).
      # In case the command failed, it is ignored. In case the same key is defined
      # both as static and dynamic, the dynamic value has priority (as long as the)
      # command does not fail.
      [meta_data.dynamic.commands]
      # Example:
      # temperature="/opt/gateway-temperature/gateway-temperature.sh"


    # Executable commands.
    #
    # The configured commands can be triggered by sending a message to the
    # ChirpStack Gateway Bridge.
    [commands]
      # Example:
      # [commands.commands.reboot]
      # max_execution_duration="1s"
      # command="/usr/bin/reboot"