{{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace "certs") }}
apiVersion: v1
kind: Secret
metadata:
  name: certs
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
type: Opaque
data:
  {{- if $existingSecret }}
    # If the secret exists, we will merge the new certificates with the existing ones
    {{- range $key, $cert := .Values._common.certificates }}
      # If the key doesn't already exist in the secret, add it
      {{- if not (hasKey $existingSecret.data $key) }}
        {{ $key }}: {{ $cert | b64enc }}
      {{- end }}
    {{- end }}
  {{- else }}
    # If the secret doesn't exist, create a new one from the values
    {{- range $key, $cert := .Values._common.certificates }}
      {{ $key }}: {{ $cert | b64enc }}
    {{- end }}
  {{- end }}
