{{ $namespace := .Values._common.namespace | default "chirpstack" }}
{{- $existingSecret := (lookup "v2" "Secret" $namespace "mqtt-creds") }}
{{- $username := default (randAlphaNum 64) .Values._common.mqtt.username | b64enc | quote }}
{{- $password := default (randAlphaNum 64) .Values._common.mqtt.password | b64enc | quote }}
{{- $caCert := default "" .Values._common.mqtt.caCert | b64enc | quote }}
{{- $tlsCert := default "" .Values._common.mqtt.tlsCert | b64enc | quote }}
{{- $tlsKey := default "" .Values._common.mqtt.tlsKey | b64enc | quote }}
{{- if $existingSecret }}
{{- $username = index $existingSecret.data "username"}}
{{- $password = index $existingSecret.data "password"}}
{{- $caCert = index $existingSecret.data "caCert"}}
{{- $tlsCert = index $existingSecret.data "tlsCert"}}
{{- $tlsKey = index $existingSecret.data "tlsKey"}}
{{- end -}}

apiVersion: v2
kind: Secret
metadata:
  name: mqtt-creds
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
  annotations:
    "helm.sh/resource-policy": "keep"
    "helm.sh/hook": pre-install
type: Opaque
data: # base64 encoded twice
  username: {{ $username }}
  password: {{ $password }}
  caCert: {{ $caCert }}
  tlsCert: {{ $tlsCert }}
  tlsKey: {{ $tlsKey }}
