apiVersion: v2
kind: ConfigMap
metadata:
  name: {{ .Values.postgres.volumes.initdb.configMap.name }}
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
data:
  initdb/001-init-chirpstack.sh: |
    #!/bin/bash
    set -e

    # Check and create role if it does not exist
    if ! psql -t -c "SELECT 1 FROM pg_roles WHERE rolname='{{ .Values._common.postgres.settings.role }}'" | grep -q 1; then
        echo "Creating role {{ .Values._common.postgres.settings.role }}"
        psql -v ON_ERROR_STOP=1 --username "{{ .Values._common.postgres.settings.postgresUser }}" <<-EOSQL
            create role {{ .Values._common.postgres.settings.role }} with login password '{{ .Values._common.postgres.settings.password }}';
        EOSQL
    else
        echo "Role {{ .Values._common.postgres.settings.role }} already exists."
    fi
  initdb/002-chirpstack_extensions.sh: |
    #!/bin/bash
    set -e

    # Check and create extensions if they do not exist
    for ext in pg_trgm hstore; do
        if ! psql -t -c "SELECT 1 FROM pg_extension WHERE extname='${ext}'" | grep -q 1; then
            echo "Creating extension ${ext}"
            psql -v ON_ERROR_STOP=1 --username "{{ .Values._common.postgres.settings.postgresUser }}" --dbname="{{ .Values._common.postgres.settings.dbName }}" <<-EOSQL
                create extension ${ext};
            EOSQL
        else
            echo "Extension ${ext} already exists."
        fi
    done
