apiVersion: v2
kind: ConfigMap
metadata:
  name: chirpstack-configuration
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
data:
  chirpstack.toml: |
    # Logging.
    [logging]

      # Log level.
      #
      # Options are: trace, debug, info, warn error.
      level={{ .Values._common.logging | default "info" }}


    # PostgreSQL configuration.
    [postgresql]

      # PostgreSQL DSN.
      #
      # Format example: postgres://<USERNAME>:<PASSWORD>@<HOSTNAME>/<DATABASE>?sslmode=<SSLMODE>.
      #
      # SSL mode options:
      #  * disable - no SSL
      #  * require - Always SSL (skip verification)
      #  * verify-ca - Always SSL (verify that the certificate presented by the server was signed by a trusted CA)
      #  * verify-full - Always SSL (verify that the certification presented by the server was signed by a trusted CA and the server host name matches the one in the certificate)
      {{- if .Values._common.postgres.external.enabled }}
      dsn="postgres://{{ $.Values._common.postgres.settings.role }}:{{ $.Values._common.postgres.settings.password }}@{{ $.Values._common.postgres.host }}/{{ $.Values._common.postgres.settings.dbName }}?sslmode={{ $.Values._common.postgres.host }}"
      {{- else }}
      dsn="postgres://{{ $.Values._common.postgres.settings.role }}:{{ $.Values._common.postgres.settings.password }}@postgres.{{ .Values._common.namespace }}.svc.cluster.local/{{ $.Values._common.postgres.settings.dbName }}?sslmode={{ $.Values._common.postgres.host }}"
      {{- end }}
      
      # Max open connections.
      #
      # This sets the max. number of open connections that are allowed in the
      # PostgreSQL connection pool.
      max_open_connections={{ .Values._common.postgres.settings.maxOpenConnections | default 10}}

      # Min idle connections.
      #
      # This sets the min. number of idle connections in the PostgreSQL connection
      # pool (0 = equal to max_open_connections).
      min_idle_connections={{ .Values._common.postgres.settings.minIdleConnections | default 0}}


    # Redis configuration.
    [redis]

      # Server address or addresses.
      #
      # Set multiple addresses when connecting to a cluster.
      {{- if .Values._common.redis.external.enabled }}
      servers=[
        "redis://{{ $.Values._common.external.redis.host }}:{{ .Values._common.external.redis.port }}/"
      ]
      {{- else }}
      servers=[
        "redis://redis.{{ $.Values._common.namespace }}.svc.cluster.local:{{ .Values.redis.service.port }}/"
      ]
      {{- end }}

      # TLS enabled.
      tls_enabled={{ .Values._common.redis.settings.tls | default false}}

      # Redis Cluster.
      #
      # Set this to true when the provided URLs are pointing to a Redis Cluster
      # instance.
      cluster=tls_enabled={{ .Values._common.redis.settings.cluster | default false }}


    # Network related configuration.
    [network]

      # Network identifier (NetID, 3 bytes) encoded as HEX (e.g. 010203).
      net_id="{{ .Values._common.netId | default "000000" }}"

      # Enabled regions.
      #
      # Multiple regions can be enabled simultaneously. Each region must match
      # the 'name' parameter of the region configuration in '[[regions]]'.
      enabled_regions=[
      {{- range $index, $region := .Values._common.region }}
            "{{ $region.name }}",
      {{- end }}
      ]


    # API interface configuration.
    [api]

      # interface:port to bind the API interface to.
      bind="0.0.0.0:{{ .Values._common.apiPort }}"

      # Secret.
      #
      # This secret is used for generating login and API tokens, make sure this
      # is never exposed. Changing this secret will invalidate all login and API
      # tokens. The following command can be used to generate a random secret:
      #   openssl rand -base64 32
      secret="{{ .Values._common.secret | default }}"


    [integration]
      enabled=["mqtt"]

      [integration.mqtt]
        server="tcp://{{ .Values._common.mqtt.host }}:{{ .Values._common.mqtt.port }}/"
        json=true

{{- range $index, $region := .Values._common.region }}
  region_{{ $region.name }}.toml: |
    {{- $filePath := printf "configurations/chirpstack/region_%s.toml" $region.name }}

    # This file contains an example EU433 configuration.
    [[regions]]

      # Name is an user-defined identifier for this region.
      name="{{ $region.name }}"

      # Common-name refers to the common-name of this region as defined by
      # the LoRa Alliance.
      common_name="{{ upper $region.name }}"


      # Gateway configuration.
      [regions.gateway]

        # Force gateways as private.
        #
        # If enabled, gateways can only be used by devices under the same tenant.
        force_gws_private={{ $region.settings.gateway.private | default false }}


        # Gateway backend configuration.
        [regions.gateway.backend]

          # The enabled backend type.
          enabled="{{ $region.settings.gateway.enabledBackend | default "mqtt" }}"

          # MQTT configuration.
          [regions.gateway.backend.mqtt]

            # Event topic template.
            event_topic="{{ $region.settings.gateway.eventTopic | default (printf "%s/gateway/+/event/+" (toString $region.name)) }}"

            # Command topic template.
            command_topic="{{ $region.settings.gateway.commandTopic | default  (printf "%s/gateway/{{ gateway_id }}/command/{{ command }}" (toString $region.name))  }}"

            # MQTT server (e.g. scheme://host:port where scheme is tcp, ssl or ws)
            server="tcp://{{ $.Values._common.mqtt.host }}:{{ $.Values._common.mqtt.port }}"

            # Connect with the given username (optional)
            username="{{ $.Values._common.mqtt.username | default "" }}"

            # Connect with the given password (optional)
            password="{{ $.Values._common.mqtt.password | default "" }}"

            # Quality of service level
            #
            # 0: at most once
            # 1: at least once
            # 2: exactly once
            #
            # Note: an increase of this value will decrease the performance.
            # For more information: https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels
            qos={{ $.Values._common.mqtt.qos | default 2 }}

            # Clean session
            #
            # Set the "clean session" flag in the connect message when this client
            # connects to an MQTT broker. By setting this flag you are indicating
            # that no messages saved by the broker for this client should be delivered.
            clean_session={{ $.Values._common.mqtt.cleanSession | default false }}

            # Client ID
            #
            # Set the client id to be used by this client when connecting to the MQTT
            # broker. A client id must be no longer than 23 characters. If left blank,
            # a random id will be generated by ChirpStack.
            client_id="{{ $.Values._common.mqtt.clientId | default "chirpstack" }}"

            # CA certificate file (optional)
            #
            # Use this when setting up a secure connection (when server uses ssl://...)
            # but the certificate used by the server is not trusted by any CA certificate
            # on the server (e.g. when self generated).
            ca_cert="{{ $.Values._common.mqtt.caCert | default "" }}"

            # TLS certificate file (optional)
            tls_cert="{{ $.Values._common.mqtt.tlsCert | default "" }}"

            # TLS key file (optional)
            tls_key="{{ $.Values._common.mqtt.tlsKey | default "" }}"


        # Gateway channel configuration.
        #
        # Note: this configuration is only used in case the gateway is using the
        # ChirpStack Concentratord daemon. In any other case, this configuration 
        # is ignored.
        {{- $regionData := $.Files.Get (printf "configurations/chirpstack/regions/region_%s.json" $region.name) | fromJson }}
        {{- if $regionData.regions }}
        {{- range $region := $regionData.regions }}
        {{- if $region.gateway }}
        {{- if $region.gateway.channels }}  # Check if channels exists in gateway
        {{- range $channel := $region.gateway.channels }}
        [[regions.gateway.channels]]
        {{- range $key, $value := $channel }}
          {{ $key }}={{ toJson $value }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}

        

      [regions.network]
        
        # Installation margin (dB) used by the ADR engine.
        #
        # A higher number means that the network-server will keep more margin,
        # resulting in a lower data-rate but decreasing the chance that the
        # device gets disconnected because it is unable to reach one of the
        # surrounded gateways.
        installation_margin={{ $region.settings.gateway.installationMargin | default 10 }}

        # RX window (Class-A).
        #
        # Set this to:
        # 0: RX1 / RX2
        # 1: RX1 only
        # 2: RX2 only
        rx_window={{ $region.settings.gateway.rxWindow | default 0 }}

        # RX1 delay (1 - 15 seconds).
        rx1_delay={{ $region.settings.gateway.rx1Delay | default 1 }}

        # RX1 data-rate offset
        rx1_dr_offset={{ $region.settings.gateway.rx1DrOffset | default 0 }}

        # RX2 data-rate
        rx2_dr={{ $region.settings.gateway.rx2Dr | default 0 }}

        # RX2 frequency (Hz)
        {{- $regionData := $.Files.Get (printf "configurations/chirpstack/regions/region_%s.json" $region.name) | fromJson }}
        {{- if $regionData.regions }}
        {{- range $region := $regionData.regions }}
        {{- if $region.network.rx2_frequency }}
        rx2_frequency={{ toJson $region.network.rx2_frequency }}
        {{- end }}
        {{- end }}
        {{- end }}

        # Prefer RX2 on RX1 data-rate less than.
        #
        # Prefer RX2 over RX1 based on the RX1 data-rate. When the RX1 data-rate
        # is smaller than the configured value, then the Network Server will
        # first try to schedule the downlink for RX2, failing that (e.g. the gateway
        # has already a payload scheduled at the RX2 timing) it will try RX1.
        rx2_prefer_on_rx1_dr_lt={{ $region.settings.gateway.rx2PreferOnRx1DrLt | default 0 }}

        # Prefer RX2 on link budget.
        #
        # When the link-budget is better for RX2 than for RX1, the Network Server will first
        # try to schedule the downlink in RX2, failing that it will try RX1.
        rx2_prefer_on_link_budget={{ $region.settings.gateway.rx2PreferOnLinkBudget | default false }}

        # Downlink TX Power (dBm)
        #
        # When set to -1, the downlink TX Power from the configured band will
        # be used.
        #
        # Please consult the LoRaWAN Regional Parameters and local regulations
        # for valid and legal options. Note that the configured TX Power must be
        # supported by your gateway(s).
        downlink_tx_power={{ $region.settings.gateway.downlinkTxPower | default -1 }}

        # ADR is disabled.
        adr_disabled={{ $region.settings.gateway.adrDisabled | default false }}

        # Minimum data-rate.
        min_dr={{ $region.settings.gateway.minDr | default 0 }}

        # Maximum data-rate.
        max_dr={{ $region.settings.gateway.max_dr | default 5 }}


        # Rejoin-request configuration (LoRaWAN 1.1)
        [regions.network.rejoin_request]

          # Request devices to periodically send rejoin-requests.
          enabled={{ $region.settings.gateway.enabled | default false }}

          # The device must send a rejoin-request type 0 at least every 2^(max_count_n + 4)
          # uplink messages. Valid values are 0 to 15.
          max_count_n={{ $region.settings.gateway.maxCount | default 0 }}

          # The device must send a rejoin-request type 0 at least every 2^(max_time_n + 10)
          # seconds. Valid values are 0 to 15.
          #
          # 0  = roughly 17 minutes
          # 15 = about 1 year
          max_time_n={{ $region.settings.gateway.maxTime | default 0 }}
        

        # Class-B configuration.
        [regions.network.class_b]

          # Ping-slot data-rate. 
          ping_slot_dr={{ $region.settings.gateway.pingSlotDr | default 0 }}

          # Ping-slot frequency (Hz)
          #
          # set this to 0 to use the default frequency plan for the configured region
          # (which could be frequency hopping).
          ping_slot_frequency={{ $region.settings.gateway.pingSlotFrequency | default 0 }}
        
        # Below is the common set of extra channels. Please make sure that these
        # channels are also supported by the gateways.
        {{- $regionData := $.Files.Get (printf "configurations/chirpstack/regions/region_%s.json" $region.name) | fromJson }}
        {{- if $regionData.regions }}
        {{- range $region := $regionData.regions }}
        {{- if $region.network }}
        {{- if $region.network.extra_channels }}  # Check if channels exists in gateway
        {{- range $channel := $region.network.extra_channels }}
        [[regions.network.extra_channels]]
        {{- range $key, $value := $channel }}
          {{ $key }}={{ toJson $value }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
        {{- end }}
{{- end }}
