apiVersion: v1
kind: Service
metadata:
  labels:
    app: chirpstack-api
  name: chirpstack-api
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
spec:
  ports:
  - name: web
    port: {{ .Values.api.service.port }}
    protocol: TCP
    targetPort: {{ .Values.api.service.port }}
  selector:
    app: chirpstack-api
  type: {{ .Values.api.service.type | default "ClusterIP" }}