{{- if not .Values._common.redis.external.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: {{ .Values._common.namespace | default "chirpstack" }}
spec:
  ports:
  - name: redis
    port: {{ .Values.redis.service.port }}
    protocol: TCP
    targetPort: {{ .Values.redis.service.port }}
  selector:
    app: redis
  type: ClusterIP
{{- end }}